networks:
    reservation-network:
        driver: bridge

services:
    web:
        container_name: reservation_web
        build:
            context: ./
            dockerfile: web.dockerfile
        volumes:
            - ./:/var/www
        ports:
            - '1241:80'
        networks:
            - reservation-network
        links:
            - app

    app:
        container_name: reservation_app
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: app.dockerfile
        restart: unless-stopped
        ports:
            - '1242:9000'
            - '${VITE_PORT:-4112}:${VITE_PORT:-4112}'
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./.env:/var/www/.env
        env_file: '.env'
        networks:
            - reservation-network
        links:
            - db

    db:
        image: mariadb:10.4
        container_name: reservation_db
        platform: linux/amd64 #for platform error on Apple M1 chips
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        ports:
            - '1243:3306'
        networks:
            - reservation-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        container_name: reservation_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            UPLOAD_LIMIT: 300M
        ports:
            - '1244:80'
        networks:
            - reservation-network